.NET/WebApplicationTest/Controllers/VoziloesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationTest.Data;
using WebApplicationTest.Models;

namespace WebApplicationTest.Controllers
{
    public class VoziloesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VoziloesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Voziloes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Vozila.Include(v => v.Tip);
            return View(await applicationDbContext.ToListAsync());
        }

        //GET /Voziloes/Expired
        public async Task<IActionResult> Expired()
        {
            if (_context.Vozila != null)
            {
                var vozilo = _context.Vozila
                .Include(v => v.Tip);
                return View(await vozilo.ToListAsync());

            } else {
                return View(); 
            }
        }

        //GET /Voziloes/Expired
        public async Task<IActionResult> Search(string searchString)
        {
            if (_context.Vozila != null)
            {
                if (!String.IsNullOrEmpty(searchString))
                {
                    var vozilo = _context.Vozila.Where(s => s.Naziv!.Contains(searchString)).Include(v => v.Tip);
                    return View(await vozilo.ToListAsync());
                } else
                { 
                    return View(); 
                }         

            }
            else
            {
                return View();
            }
        }

        //GET /Voziloes/SearchDate
        public async Task<IActionResult> SearchDate(DateTime startDate, DateTime endDate)
        {
            if (_context.Vozila != null)
            {
                if (startDate != DateTime.MinValue && endDate != DateTime.MinValue)
                {
                    var vozilo = _context.Vozila.Where(s => (startDate <= s.DatumIsteka.Date && s.DatumIsteka.Date <= endDate)).Include(v => v.Tip);
                    return View(await vozilo.ToListAsync());

                } else if(endDate != DateTime.MinValue && startDate == DateTime.MinValue)
                {
                    var vozilo = _context.Vozila.Where(s => s.DatumIsteka.Date <= endDate).Include(v => v.Tip);
                    return View(await vozilo.ToListAsync());
                }
          
                else if (startDate != DateTime.MinValue && endDate == DateTime.MinValue)
                {
                    var vozilo = _context.Vozila.Where(s => startDate <= s.DatumIsteka.Date).Include(v => v.Tip);
                    return View(await vozilo.ToListAsync());
                }
                else
                {
                    return View();
                }

            }
            else
            {
                return View();
            }
        }


        // GET: Voziloes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vozila == null)
            {
                return NotFound();
            }

            var vozilo = await _context.Vozila
                .Include(v => v.Tip)
                .FirstOrDefaultAsync(m => m.idVozila == id);
            if (vozilo == null)
            {
                return NotFound();
            }

            return View(vozilo);
        }

        // GET: Voziloes/Create
        public IActionResult Create()
        {
            ViewData["TipID"] = new SelectList(_context.TipoviVozila, "IdTip", "Naziv");
            return View();
        }

        // POST: Voziloes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("idVozila,Naziv,TipID,RegOznaka,DatumIsteka")] Vozilo vozilo)
        {
            //if (ModelState.IsValid)
            //{
                _context.Add(vozilo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            //}
            ViewData["TipID"] = new SelectList(_context.TipoviVozila, "IdTip", "Naziv", vozilo.TipID);
            return View(vozilo);
        }

        // GET: Voziloes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vozila == null)
            {
                return NotFound();
            }

            var vozilo = await _context.Vozila.FindAsync(id);
            if (vozilo == null)
            {
                return NotFound();
            }
            ViewData["TipID"] = new SelectList(_context.TipoviVozila, "IdTip", "Naziv", vozilo.TipID);
            return View(vozilo);
        }

        // POST: Voziloes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("idVozila,Naziv,TipID,RegOznaka,DatumIsteka")] Vozilo vozilo)
        {
            if (id != vozilo.idVozila)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vozilo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VoziloExists(vozilo.idVozila))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipID"] = new SelectList(_context.TipoviVozila, "IdTip", "Naziv", vozilo.TipID);
            return View(vozilo);
        }

        // GET: Voziloes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vozila == null)
            {
                return NotFound();
            }

            var vozilo = await _context.Vozila
                .Include(v => v.Tip)
                .FirstOrDefaultAsync(m => m.idVozila == id);
            if (vozilo == null)
            {
                return NotFound();
            }

            return View(vozilo);
        }

        // POST: Voziloes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vozila == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Vozila'  is null.");
            }
            var vozilo = await _context.Vozila.FindAsync(id);
            if (vozilo != null)
            {
                _context.Vozila.Remove(vozilo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VoziloExists(int id)
        {
            return (_context.Vozila?.Any(e => e.idVozila == id)).GetValueOrDefault();
        }

        
    }
}

.NET/WebApplicationTest/Views/Voziloes/Create.cshtml
@model WebApplicationTest.Models.Vozilo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Vozilo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipID" class="control-label"></label>
                <select asp-for="TipID" class ="form-control" asp-items="ViewBag.TipID"></select>
            </div>
            <div class="form-group">
                <label asp-for="RegOznaka" class="control-label"></label>
                <input asp-for="RegOznaka" class="form-control" />
                <span asp-validation-for="RegOznaka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumIsteka" class="control-label"></label>
                <input asp-for="DatumIsteka" class="form-control" />
                <span asp-validation-for="DatumIsteka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

.NET/WebApplicationTest/Views/Voziloes/Delete.cshtml
@model WebApplicationTest.Models.Vozilo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vozilo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tip.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegOznaka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegOznaka)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumIsteka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumIsteka)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="idVozila" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

.NET/WebApplicationTest/Views/Voziloes/Details.cshtml
@model WebApplicationTest.Models.Vozilo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Vozilo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tip.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegOznaka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegOznaka)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumIsteka)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumIsteka)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.idVozila">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

.NET/WebApplicationTest/Views/Voziloes/Edit.cshtml
@model WebApplicationTest.Models.Vozilo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Vozilo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="idVozila" />
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipID" class="control-label"></label>
                <select asp-for="TipID" class="form-control" asp-items="ViewBag.TipID"></select>
                <span asp-validation-for="TipID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegOznaka" class="control-label"></label>
                <input asp-for="RegOznaka" class="form-control" />
                <span asp-validation-for="RegOznaka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumIsteka" class="control-label"></label>
                <input asp-for="DatumIsteka" class="form-control" />
                <span asp-validation-for="DatumIsteka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

.NET/WebApplicationTest/Views/Voziloes/Expired.cshtml
@model IEnumerable<WebApplicationTest.Models.Vozilo>
@{
    ViewData["Title"] = "Expired";
}

<h1>Expired Vehicles</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naziv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegOznaka)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumIsteka)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
         @if (DateTime.Now > item.DatumIsteka)
        {
            <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tip.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegOznaka)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumIsteka)
            </td>
            </tr>
        }
}
    </tbody>
</table>

.NET/WebApplicationTest/Views/Voziloes/Index.cshtml
@model IEnumerable<WebApplicationTest.Models.Vozilo>

@{
    ViewData["Title"] = "Pregled vozila / Vehicles overwiev";
}

<h1>Pregled vozila / Vehicles overwiev</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naziv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegOznaka)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumIsteka)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tip.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegOznaka)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatumIsteka)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.idVozila">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.idVozila">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.idVozila">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

.NET/WebApplicationTest/Views/Voziloes/Search.cshtml
@model IEnumerable<WebApplicationTest.Models.Vozilo>
@{
    ViewData["Title"] = "Search";
}

<h1>Search</h1>

<div>
    <form asp-controller="Voziloes" asp-action="Search">
        <div class="input-group">
            <div>
                <input type="text" name="SearchString" />
            </div>
            <div>
                <input type="submit" value="Search" />
            </div>
            
        </div>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naziv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegOznaka)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumIsteka)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tip.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RegOznaka)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DatumIsteka)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.idVozila">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.idVozila">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.idVozila">Delete</a>
                    </td>
                </tr>
            }
        }
       
    </tbody>
</table>

.NET/WebApplicationTest/Views/Voziloes/SearchDate.cshtml
@model IEnumerable<WebApplicationTest.Models.Vozilo>

@{
    ViewData["Title"] = "SearchDate";
}

<h1>Search By Date</h1>

<div>
    <form asp-controller="Voziloes" asp-action="SearchDate">
        <div class="input-group">
            <div>
                <input type="date" name="startDate" />
            </div>
            <div>
                <input type="date" name="endDate" />
            </div>
            <div>
                <input type="submit" value="Search" />
            </div>

        </div>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naziv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegOznaka)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumIsteka)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tip.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RegOznaka)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DatumIsteka)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.idVozila">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.idVozila">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.idVozila">Delete</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>